// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh4u5nN4nhnX870bqneDbcHNb9t60Gi00',
    appId: '1:166582404431:web:c0808768165b20d209b13a',
    messagingSenderId: '166582404431',
    projectId: 'medicheck-157f1',
    authDomain: 'medicheck-157f1.firebaseapp.com',
    storageBucket: 'medicheck-157f1.firebasestorage.app',
    measurementId: 'G-CRCCER3DMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMqEtPO6H_abi-085BOaL1vmO5kOvvTs',
    appId: '1:166582404431:android:691050f86462a46709b13a',
    messagingSenderId: '166582404431',
    projectId: 'medicheck-157f1',
    storageBucket: 'medicheck-157f1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh4u5nN4nhnX870bqneDbcHNb9t60Gi00',
    appId: '1:166582404431:web:d3b2a33a078ecff309b13a',
    messagingSenderId: '166582404431',
    projectId: 'medicheck-157f1',
    authDomain: 'medicheck-157f1.firebaseapp.com',
    storageBucket: 'medicheck-157f1.firebasestorage.app',
    measurementId: 'G-5TNJQ7WS99',
  );
}
